Bookcase.seed_once(:name,
  { name: 'Bookcase A', description: "Here's a description", shelves_count: 4 },
  { name: 'Bookcase B', description: "Here's a description", shelves_count: 3 },
  { name: 'Bookcase C', description: "Here's a description", shelves_count: 4 },
  { name: 'Bookcase D', description: "Here's a description", shelves_count: 8 },
  { name: 'Bookcase E', description: "Here's a description", shelves_count: 4 },
  { name: 'Bookcase F', description: "Here's a description", shelves_count: 3 },
  { name: 'Bookcase G', description: "Here's a description", shelves_count: 4 },
  { name: 'Bookcase H', description: "Here's a description", shelves_count: 2 },
  { name: 'Bookcase I', description: "Here's a description", shelves_count: 4 },
  { name: 'Bookcase J', description: "Here's a description", shelves_count: 6 },
  { name: 'Bookcase K', description: "Here's a description", shelves_count: 4 },
  { name: 'Bookcase L', description: "Here's a description", shelves_count: 5 },
  { name: 'Bookcase M', description: "Here's a description", shelves_count: 4 }
)